## import numpy

In [1]:
import numpy as np

## The basic

In [96]:
#one dimension
a = np.array([1,2,3],dtype = np.int32)
print(a)

[1 2 3]


In [51]:
#Two dimension
b = np.array([[4,5,6],[7,8,9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [32]:
#Get dimension (it shows the how many dimension are in the array)
a.ndim

1

In [38]:
#Get shapes (it shows how many row and column are in the array)
b.shape

(2, 3)

In [98]:
#Get type
a.dtype
#b.dtype


dtype('int32')

In [100]:
#Get size
a.itemsize
#b.itemsize

4

In [118]:
#Get total size (it shows the total length of the list)
a.size * a.itemsize
#b.size * b.itemsize

12

## Accessing/Changing specific elements,rows,columns etc

In [17]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#Get a specific element (row,column)
c[1,2]

10

In [25]:
#Get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#Get specific column
c[:,5]

array([ 6, 13])

In [49]:
#Getting a little fancy [starting index,ending index,stepsize(how many element want to skip)]
c[1,1:5:2]

array([ 9, 10, 11, 12])

In [65]:
#modify the element
c[1,6]=15
print(c)

c[:,2:]=10
print(c)

[[ 1  2 15  4  5  6  7]
 [ 8  9 10 11 12 13 15]]
[[ 1  2 10 10 10 10 10]
 [ 8  9 10 10 10 10 10]]


#### 3d example

In [98]:
d = np.array([[[1,2,],[3,4]],[[4,5],[6,7]]])
print(d)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [110]:
#Geting specific element
d[0,1,0]


3

In [112]:
#modify the element 
d[:,1,:]=[[9,9],[8,8]]
d

array([[[1, 2],
        [9, 9]],

       [[4, 5],
        [8, 8]]])

## initilizing different types of arrays

In [8]:
# All 0s matrix
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#All in 1s matrix
np.ones((8,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#Any other numbers
np.full((4,2),29)

array([[29, 29],
       [29, 29],
       [29, 29],
       [29, 29]])

In [16]:
# anu other numbers (full_like)
np.full_like(b,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [22]:
#Random decimal numbers
np.random.rand(8,4)

array([[0.3318271 , 0.39272654, 0.70538052, 0.20745062],
       [0.14883843, 0.65135305, 0.60006259, 0.16612235],
       [0.34515333, 0.34905053, 0.45034361, 0.4256183 ],
       [0.6050741 , 0.61924591, 0.64783828, 0.77196424],
       [0.50870983, 0.48245841, 0.93924551, 0.15853855],
       [0.05128106, 0.23664242, 0.07413342, 0.18669048],
       [0.09654779, 0.28393989, 0.36444939, 0.86155075],
       [0.06614698, 0.55739152, 0.74932513, 0.34695503]])

In [36]:
# Random integer values
np.random.randint(7,size = (3,3)) #(7 means range of the integer, size means (3,3) row,column)

array([[1, 2, 0],
       [6, 3, 6],
       [0, 5, 6]])

In [39]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
arr = np.array([[1,2,3]])
rl = np.repeat(arr,3,axis = 0)
print(rl)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [11]:
x = np.ones((5,5))
print(output)

y = np.zeros((3,3))
y[1,1] = 9
print(y)

x[1:4,1:4] = y
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## copying the array

In [41]:
a = np.array([4,5,6])
b = a.copy()
b[0] = 100
print(a)
print(b)

[4 5 6]
[100   5   6]


## Mathematics

In [43]:
c = np.array([1,2,3,4,5,6])
print(c)

[1 2 3 4 5 6]


In [53]:
c + 5

array([ 6,  7,  8,  9, 10, 11])

In [55]:
c - 6

array([-5, -4, -3, -2, -1,  0])

In [57]:
c * 9

array([ 9, 18, 27, 36, 45, 54])

In [51]:
c / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 ])

In [65]:
#Take the sin
np.sin(a)
np.cos(a)
np.tan(a)

array([ 1.15782128, -3.38051501, -0.29100619])